### ISSUE TITLE
Feat: Add Hero Section in template

### ISSUE THREAD

**Issue by rizwan2000rm** [rizwan2000rm/foodles#2]
Add a hero section as shown in the design below.
![Design](https://raw.githubusercontent.com/rizwan2000rm/foodles/master/uploads/foodles.webp)

**Comment by adnan2212** [comment]
> Add a hero section as shown in the design below.
> ![Design](https://raw.githubusercontent.com/rizwan2000rm/foodles/master/uploads/foodles.webp)

I want to be assigned

**Comment by SaistaShaikh** [comment]
i want to get assigned
